server:
  port: 9200
spring:
  application:
    name: gmall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 47.99.113.40:1111
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由 可以实现服务的负载均衡
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://gmall-user-auth #匹配后提供服务的路由地址  需要注意的是uri的协议为lb，表示启用Gateway的负载均衡功能。
          predicates:
            - Path=/gmall/profile/**         # 断言，路径相匹配的进行路由

        #- id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
         # uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          #predicates:
            # 断言 只有符合这些断言条件才能匹配路由
            # Path After Cookie Header 都是断言的一种
            #- Path=/payment/lb/**         # 断言，路径相匹配的进行路由
            #- After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai] # 表示在什么时间之后才能访问该路由
            #- Cookie=username,zzyy
            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
            #- Method=Get 表示get请求
            #- Query=username, +/d 查询参数
          #filters: 过滤器
          #  - AddRequestHeader=X-Request-red, blue